### ISSUE TITLE
Ability to ignore audiobook libraries

### ISSUE THREAD

**Issue by ordinarygulp** [simonxciv/eavesdrop.fm#2]
Since audiobook plays are not really in the purview of "scrobbling" services (at least Listenbrainz), I think it'd be a great addition to allow users to filter out certain libraries from their server, to not submit listen data.

**Comment by Kanekid2m** [comment]
> Since audiobook plays are not really in the purview of "scrobbling" services (at least Listenbrainz), I think it'd be a great addition to allow users to filter out certain libraries from their server, to not submit listen data.

FINALLY found u xD I really was looking for u overall and now recognized u with the pic. Can you please email me at d2mds21@gmail.com ? I did not find ur email on ur github and I really want to ask you something. Sorry for contacting u this way!

**Comment by simonxciv** [comment]
Adding a note to provide some context of where this issue's at:

To be able to filter webhook events based on library source, we need to be able to provide an "allow list" or similar in the webhook URL parameters, and then filter out libraries by matching the webhook payload to the parameter.

Unfortunately at the moment, Plex webhooks don't provide any information about the library source, so this isn't possible right now. I've raised an issue internally with Plex, and will keep track of any progress here.

Quasar in the Plex forums has also [requested this](https://forums.plex.tv/t/eavesdrop-fm-sync-plex-music-listens-to-listenbrainz/580467/20).

**Comment by simonxciv** [comment]
Issue resolved by https://github.com/simonxciv/eavesdrop.fm/commit/d379d14154fd5d0bd1a2ec998172a3082b9b86fa
