### ISSUE TITLE
verifying plex username

### ISSUE THREAD

**Issue by mlincoln** [simonxciv/eavesdrop.fm#6]
I set up my webhook and believe I checked all the necessary boxes. However, nothing is being logged to my account. I wonder if:
1. I am entering my username correctly
2. There could be issues when there's a space in the username

My plex username is "firstname lastname"
![Screen Shot 2020-10-02 at 9 55 54 AM](https://user-images.githubusercontent.com/796807/94950400-6ec66280-0497-11eb-9bd6-85cbfa3a9530.png)
Is this exactly how it should be entered in the textbox to create the webhook?

**Comment by simonxciv** [comment]
Thanks for the heads up! I'm pretty sure I know what's going on here, and it should be a simple fix. I'll take a look shortly!

**Comment by simonxciv** [comment]
Hi @mlincoln,

You were doing the right thing :) I believe I've fixed this issue now. I wasn't properly encoding and decoding the URL string.

In your Plex webhook, replace the space with `%20`, and your webhook should start working. Alternatively, you can also re-create the webhook by going to https://eavesdrop.fm, hard refreshing the page to clear your cache (in most browsers, that's shift+refresh), and going through the steps once more, making sure to delete the old webhook.

I wasn't able to test the fix, as I don't have a Plex Pass username with a space in it (and the process to edit the username is painful with all my connected apps), so if you're still seeing issues, please let me know!
