### ISSUE TITLE
Webhook: Error delivering payload

### ISSUE THREAD

**Issue by andyforceno** [simonxciv/eavesdrop.fm#7]
I have Plex submitting play information to both last.fm and listenbrainz, and I recently noticed a large disparity in the number of track plays being reported by both services (far less by listenbrainz).

I'm seeing the following error in my Plex logs related to the eavesdrop.fm webhook I have setup: 

`Webhook: Error delivering payload to https://eavesdrop.fm/?token=xxxxxxxxxxxxxxxxxxxx90d-5d87ff174de9&user=t4exanadu: 500`

Let me know if I can provide more information. "Error delivering payload" isn't especially specific. Will debug logging in Plex increase the verbosity of webhook activity logging?

**Comment by andyforceno** [comment]
I'm going to close this issue, because I don't really have any more information to provide and I'm not seeing the error any longer. I think the missing tracks might be times when my phone doesn't have a connection with my plex server (I listen to music downloaded to my phone via the plexamp app), but I'm not sure. It seems like Plex only logs webhooks related information if there is an error. Enabling verbose debug logging doesn't provide any more relevant information.

**Comment by djdembeck** [comment]
Yes, since eavesdrop is a webhook, it only gets playing status when you are connected and streaming from a server.

**Comment by simonxciv** [comment]
Thanks for the report @andyforceno.

As you say, the error isn't very specific, but I have a couple of ideas. I don't think verbose logging would provide much more insight. I'll take a look into it shortly, and let you know if I need any further information.
